services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_HOST: flask-postgres-rds.creu6a2eemwr.ap-south-1.rds.amazonaws.com
    restart: always
