services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: always

  web:
    build: .
    expose:
      - "5000"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_HOST: flask-postgres-rds.creu6a2eemwr.ap-south-1.rds.amazonaws.com
    restart: always
